"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

const capabilities = [
  ["reference_to_image", "商品图 / 详情图"],
  ["multi_reference_to_image", "模特多角度"],
  ["virtual_try_on", "虚拟试穿"],
] as const;

export function ModelForm(){const router=useRouter();const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const form=event.currentTarget;const data=new FormData(form);const provider=String(data.get("provider"));const selected=capabilities.map(([value])=>value).filter(value=>data.get(value)==="on");const response=await fetch("/api/backend/models",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:data.get("name"),provider,model_id:data.get("model_id"),base_url:data.get("base_url")||null,api_key:data.get("api_key")||null,capabilities:selected})});if(response.ok){form.reset();setMessage("模型配置已保存，密钥不会再次显示");router.refresh();}else setMessage("保存失败，请检查配置和至少一项模型能力");setBusy(false);}return <form onSubmit={submit} className="form-grid" aria-busy={busy}><div><label className="field-label mb-2" htmlFor="model-name">配置名称</label><input className="field" id="model-name" name="name" placeholder="配置名称" required/></div><div><label className="field-label mb-2" htmlFor="provider">服务类型</label><select className="field" id="provider" name="provider"><option value="mock">Mock（本地验收）</option><option value="generic_http">通用 HTTP API</option></select></div><div><label className="field-label mb-2" htmlFor="model-id">模型 ID</label><input className="field" id="model-id" name="model_id" placeholder="模型 ID" required/></div><div><label className="field-label mb-2" htmlFor="base-url">API Base URL</label><input className="field" id="base-url" name="base_url" placeholder="API Base URL（Mock 可留空）"/></div><div><label className="field-label mb-2" htmlFor="api-key">API KEY</label><input className="field" id="api-key" name="api_key" type="password" autoComplete="new-password" placeholder="API KEY（加密保存）"/></div><fieldset className="rounded-xl border border-white/10 p-4"><legend className="px-2 text-xs font-semibold text-slate-300">模型能力</legend><div className="grid gap-3">{capabilities.map(([value,label],index)=><label className="flex min-h-11 cursor-pointer items-center gap-3 text-sm text-slate-300" key={value}><input type="checkbox" name={value} defaultChecked={index===0}/><span>{label}</span></label>)}</div></fieldset><button className="primary-button" disabled={busy}>{busy?"保存中…":"保存模型"}</button><p className="min-h-5 text-xs text-slate-400" role="status" aria-live="polite">{message}</p></form>;}
